# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check-In Action

on:
    schedule:
        - cron: '32 3 * * 1-5'
#     workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - uses: nanasess/setup-chromedriver@v1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present

            - name: Check-In
              run: node ./dist/index.js
              env:
                  ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
                  ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
                  EXECUTION_STATUS: check-in
                  SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
            - name: update cookies
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: cookies.json
                  commit-msg: 'ci: cookies'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
